### ISSUE TITLE
Unable to remove/clear value from vault record fields

### ISSUE THREAD

**Issue by sboschman** [topicuskeyhub/terraform-provider-keyhub#5]
Removing (or clearing) the value from optional vault record fields like url and username does not work. Removing an optional comment field as the password field is set does not work either.

Initial resource applied with tf:
```
resource "keyhub_vaultrecord" "my_vault_record" {
  groupuuid = module.vars.env.keyhub_group
  name = "My VaultRecord"
  url = "https://example.com"
  username = "me"
  password = "1234"
  comment = "foo"
}
```

Trying to remove the value from some field:
```
resource "keyhub_vaultrecord" "my_vault_record" {
  groupuuid = module.vars.env.keyhub_group
  name = "My VaultRecord"
  url = ""
  # username = "me"  (resource attribute removed)
  password = "1234"
  # comment = ""
}
```

Both options, removing the attribute or setting the attribute to an empty string, do not work. A `tf apply` does run the following:
```
  # keyhub_vaultrecord.my_vault_record will be updated in-place
  ~ resource "keyhub_vaultrecord" "my_vault_record" {
        id        = "9999999"
        name      = "My VaultRecord"
      ~ url       = "https://example.com" -> ""
      - username  = "me" -> null
      - comment = "foo" -> null
        # (5 unchanged attributes hidden)
    }
```

On the KeyHub side an audit message is logged for a change to the vault record, but nothing has changed. KeyHub shows the initial values and a `tf plan` / `tf apply` keep showing that a change was made and an action has to be performed.

**Comment by hielkehoeve** [comment]
Fixed in v1.0.2
